name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './src'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Config SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible
        working-directory: ./src
        run: |
          ansible-playbook -i "${{ secrets.VPS_HOST }}," \
          -u ${{ secrets.VPS_USERNAME }} \
          ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
